name: oneflow-dev-clang10-v2
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - autoconf=2.69=pl526hebd4dad_5
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.17.1=h27cfd23_0
  - ca-certificates=2021.7.5=h06a4308_1
  - certifi=2021.5.30=py38h06a4308_0
  - clang=10.0.1=default_hb85057a_2
  - clangxx=10.0.1=default_hb85057a_2
  - cmake=3.18.2=ha30ef3c_0
  - expat=2.4.1=h2531618_2
  - krb5=1.19.2=hac12032_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libclang-cpp10=10.0.1=default_hb85057a_2
  - libcurl=7.78.0=h0b77cf5_0
  - libedit=3.1.20210216=h27cfd23_1
  - libev=4.33=h7b6447c_0
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libllvm10=10.0.1=hbcb73fb_5
  - libnghttp2=1.41.0=hf8bcb03_2
  - libopenblas-static=0.3.13=h06a4308_0
  - libssh2=1.9.0=h1ba5d50_1
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtool=2.4.6=h7b6447c_1005
  - libuv=1.40.0=h7b6447c_0
  - lld=10.0.1=h2295124_0
  - lz4-c=1.9.3=h295c915_1
  - m4=1.4.18=h4e445db_0
  - nasm=2.13.03=h7b6447c_1
  - ncurses=6.2=he6710b0_1
  - ninja=1.10.2=hff7bd54_1
  - openssl=1.1.1k=h27cfd23_0
  - perl=5.26.2=h14c3975_0
  - pip=21.2.2=py38h06a4308_0
  - python=3.8.11=h12debd9_0_cpython
  - readline=8.1=h27cfd23_0
  - rhash=1.4.1=h3c74f83_1
  - sccache=0.2.15=h9b69904_0
  - setuptools=52.0.0=py38h06a4308_0
  - sqlite=3.36.0=hc218d9a_0
  - tk=8.6.10=hbc83047_0
  - wheel=0.37.0=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=haebb681_0
variables:
  CC: clang
  CXX: clang++
